#:schema node_modules/wrangler/config-schema.json
name = "supermemory-web"
compatibility_date = "2025-03-12"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "METADATA_KV"
id = "9c54d2c135214731b501bc500786d1d2"

[[kv_namespaces]]
binding = "ENCRYPTED_TOKENS"
id = "38de19a055524e23aebebf59857a1547"
preview_id = "38de19a055524e23aebebf59857a1547"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "supermemory-images"


[placement]
mode = "smart"

