name = "supermemory-backend"
main = "src/index.tsx"
compatibility_date = "2024-10-11"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"
binding = "ASSETS"


[observability]
enabled = true

[placement]
mode = "smart"

[ai]
binding = "AI"

[[workflows]]
name = "content-workflow-supermemory"
binding = "CONTENT_WORKFLOW"
class_name = "ContentWorkflow"


[[kv_namespaces]]
binding= "MD_CACHE"
id = "6adef6aadf67492ba7a6d0d9c13f7cd4"
preview_id = "6adef6aadf67492ba7a6d0d9c13f7cd4"

[[kv_namespaces]]
binding = "ENCRYPTED_TOKENS"
id = "38de19a055524e23aebebf59857a1547"
preview_id = "38de19a055524e23aebebf59857a1547"



[[unsafe.bindings]]
name = "EMAIL_LIMITER"
type = "ratelimit"
namespace_id = "2114284"
simple = { limit = 1, period = 60 }

tail_consumers = [{service = "supermemory-backend-tail"}]

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "DurableObjectRateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectRateLimiter"]

